---
swagger: "2.0"
info:
  description: This is the PGi Client API
  version: 1.0.0
  title: PGi Client API
  contact:
    email: mark.peppers@pgi.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /mpeppers/PGiClientAPI/1.0.0
tags:
- name: internal
  description: Internal PGi admin calls
- name: external
  description: API calls available to external resources
schemes:
- https
paths:
  /provider/{id}:
    get:
      tags:
      - internal
      - external
      summary: Get a Provider by Id
      description: return the requested Provider
      operationId: getProvider
      parameters:
      - name: id
        in: path
        description: Provider Id
        required: true
        type: string
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/Provider'
        404:
          description: provider not found
    delete:
      tags:
      - internal
      summary: deactivate a provider by Id
      operationId: deleteProvider
      parameters:
      - name: id
        in: path
        description: Provider Id
        required: true
        type: string
      responses:
        200:
          description: success
        202:
          description: provider already deactivated
        404:
          description: provider not found
  /provider/reactivate/{id}:
    put:
      tags:
      - internal
      summary: reactivate a Provider by Id
      operationId: reactivateProvider
      parameters:
      - name: id
        in: path
        description: Provider Id
        required: true
        type: string
      responses:
        200:
          description: success
        202:
          description: provider already active
        404:
          description: provider not found
  /provider:
    post:
      tags:
      - internal
      - external
      summary: adds a Provider
      operationId: addProvider
      parameters:
      - in: body
        name: newProvider
        description: provider to add
        required: false
        schema:
          $ref: '#/definitions/Provider'
      responses:
        201:
          description: provider created
        400:
          description: invalid input, object invalid
    put:
      tags:
      - internal
      - external
      summary: modifies a Provider
      operationId: modifyProvider
      parameters:
      - in: body
        name: updatedProvider
        description: updated provider
        required: false
        schema:
          $ref: '#/definitions/Provider'
      responses:
        200:
          description: provider updated
          schema:
            $ref: '#/definitions/Provider'
        404:
          description: provider not found
  /enterprise/{id}:
    get:
      tags:
      - internal
      - external
      summary: Get an Enterprise by Id
      description: return the requested Enterprise
      operationId: getEnterprise
      parameters:
      - name: id
        in: path
        description: Enterprise Id
        required: true
        type: string
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/Enterprise'
        404:
          description: enterprise not found
    delete:
      tags:
      - internal
      summary: deactivate a enterprise by Id
      operationId: deleteEnterprise
      parameters:
      - name: id
        in: path
        description: Enterprise Id
        required: true
        type: string
      responses:
        200:
          description: success
        202:
          description: enterprise already deactivated
        404:
          description: enterprise not found
  /enterprise/reactivate/{id}:
    put:
      tags:
      - internal
      summary: reactivate an Enterprise by Id
      operationId: reactivateEnterprise
      parameters:
      - name: id
        in: path
        description: Enterprise Id
        required: true
        type: string
      responses:
        200:
          description: success
        202:
          description: enterprise already active
        404:
          description: enterprise not found
  /enterprise:
    post:
      tags:
      - internal
      - external
      summary: adds an Enterprise
      operationId: addEnterprise
      parameters:
      - in: body
        name: newEnterprise
        description: enterprise to add
        required: false
        schema:
          $ref: '#/definitions/Enterprise'
      responses:
        201:
          description: enterprise created
        400:
          description: invalid input, object invalid
    put:
      tags:
      - internal
      - external
      summary: modifies an Enterprise
      operationId: modifyEnterprise
      parameters:
      - in: body
        name: updatedEnterprise
        description: updated enterprise
        required: false
        schema:
          $ref: '#/definitions/Enterprise'
      responses:
        200:
          description: enterprise updated
          schema:
            $ref: '#/definitions/Enterprise'
        404:
          description: enterprise not found
  /corpcust/{id}:
    get:
      tags:
      - internal
      - external
      summary: Get a Corporate Customer by Id
      description: return the requested Corporate Customer
      operationId: getCorpCust
      parameters:
      - name: id
        in: path
        description: Corporate Customer Id
        required: true
        type: string
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/CorpCust'
        404:
          description: corporate customer not found
    delete:
      tags:
      - internal
      summary: deactivate a corporate customer by Id
      operationId: deleteCorpCust
      parameters:
      - name: id
        in: path
        description: Corporate Customer Id
        required: true
        type: string
      responses:
        200:
          description: success
        202:
          description: corporate customer already deactivated
        404:
          description: corporate customer not found
  /corpcust/reactivate/{id}:
    put:
      tags:
      - internal
      summary: reactivate a Corporate Customer by Id
      operationId: reactivateCorpCust
      parameters:
      - name: id
        in: path
        description: Corporate Customer Id
        required: true
        type: string
      responses:
        200:
          description: success
        202:
          description: corporate customer already active
        404:
          description: corporate customer not found
  /corpcust:
    post:
      tags:
      - internal
      - external
      summary: adds a Corporate Customer
      operationId: addCorpCust
      parameters:
      - in: body
        name: newCorpCust
        description: corporate customer to add
        required: false
        schema:
          $ref: '#/definitions/CorpCust'
      responses:
        201:
          description: corporate customer created
        400:
          description: invalid input, object invalid
    put:
      tags:
      - internal
      - external
      summary: modifies a Corporate Customer
      operationId: modifyCorpCust
      parameters:
      - in: body
        name: updatedCorpCust
        description: updated corporate customer
        required: false
        schema:
          $ref: '#/definitions/CorpCust'
      responses:
        200:
          description: corporate customer updated
          schema:
            $ref: '#/definitions/CorpCust'
        404:
          description: corporate customer not found
  /company/{id}:
    get:
      tags:
      - internal
      - external
      summary: Get a Company by Id
      description: return the requested Company
      operationId: getCompany
      parameters:
      - name: id
        in: path
        description: Company Id
        required: true
        type: string
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/Company'
        404:
          description: company not found
    delete:
      tags:
      - internal
      summary: deactivate a company by Id
      operationId: deleteCompany
      parameters:
      - name: id
        in: path
        description: Company Id
        required: true
        type: string
      responses:
        200:
          description: success
        202:
          description: company already deactivated
        404:
          description: company not found
  /company/reactivate/{id}:
    put:
      tags:
      - internal
      summary: reactivate a Company by Id
      operationId: reactivateCompany
      parameters:
      - name: id
        in: path
        description: Company Id
        required: true
        type: string
      responses:
        200:
          description: success
        202:
          description: company already active
        404:
          description: company not found
  /company:
    post:
      tags:
      - internal
      - external
      summary: adds a Company
      operationId: addCompany
      parameters:
      - in: body
        name: newCompany
        description: company to add
        required: false
        schema:
          $ref: '#/definitions/Company'
      responses:
        201:
          description: company created
        400:
          description: invalid input, object invalid
    put:
      tags:
      - internal
      - external
      summary: modifies a Company
      operationId: modifyCompany
      parameters:
      - in: body
        name: updatedCompany
        description: updated company
        required: false
        schema:
          $ref: '#/definitions/Company'
      responses:
        200:
          description: company updated
          schema:
            $ref: '#/definitions/Company'
        404:
          description: company not found
  /client/{id}:
    get:
      tags:
      - internal
      - external
      summary: Get a Client by Id
      description: return the requested Client
      operationId: getClient
      parameters:
      - name: id
        in: path
        description: Client Id
        required: true
        type: string
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/Client'
        404:
          description: client not found
    delete:
      tags:
      - internal
      summary: deactivate a client by Id
      operationId: deleteClient
      parameters:
      - name: id
        in: path
        description: Client Id
        required: true
        type: string
      responses:
        200:
          description: success
        202:
          description: client already deactivated
        404:
          description: client not found
  /client/reactivate/{id}:
    put:
      tags:
      - internal
      summary: reactivate a Client by Id
      operationId: reactivateClient
      parameters:
      - name: id
        in: path
        description: Client Id
        required: true
        type: string
      responses:
        200:
          description: success
        202:
          description: client already active
        404:
          description: client not found
  /client:
    post:
      tags:
      - internal
      - external
      summary: adds a Client
      operationId: addClient
      parameters:
      - in: body
        name: newClient
        description: client to add
        required: false
        schema:
          $ref: '#/definitions/Client'
      responses:
        201:
          description: client created
        400:
          description: invalid input, object invalid
    put:
      tags:
      - internal
      - external
      summary: modifies a Client
      operationId: modifyClient
      parameters:
      - in: body
        name: updatedClient
        description: updated client
        required: false
        schema:
          $ref: '#/definitions/Client'
      responses:
        200:
          description: client updated
          schema:
            $ref: '#/definitions/Client'
        404:
          description: client not found
  /clients:
    get:
      tags:
      - internal
      - external
      summary: get list of Clients by entity
      operationId: getClients
      parameters:
      - name: provider
        in: query
        description: provider id
        required: false
        type: string
      - name: enterprise
        in: query
        description: enterprise id
        required: false
        type: string
      - name: corpcust
        in: query
        description: corporate customer id
        required: false
        type: string
      - name: company
        in: query
        description: company id
        required: false
        type: string
      responses:
        200:
          description: client list
          schema:
            type: array
            items:
              $ref: '#/definitions/Client'
        400:
          description: bad request - only one entity allowed in query
        404:
          description: no matching clients found
definitions:
  Provider:
    type: object
    properties:
      id:
        type: string
        format: uuid
        description: System generated UUID
      externalId:
        type: string
        description: Unique identifier of provider in source system.
      name:
        type: string
        description: Human readable name for use in identifying the provider.
      startDate:
        type: string
        format: date
        description: Date that this provider is created
      endDate:
        type: string
        format: date
        description: If the provider is 'deleted', then the end date is set.
        readOnly: true
    example:
      endDate: 2000-01-23
      name: name
      externalId: externalId
      id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      startDate: 2000-01-23
  Enterprise:
    type: object
    properties:
      id:
        type: string
        format: uuid
        description: System generated UUID
      name:
        type: string
        description: Human readable name for use in identifying the enterprise.
      startDate:
        type: string
        format: date
        description: Date that this enterprise is created
      endDate:
        type: string
        format: date
        description: If the enterprise is 'deleted', then the end date is set.
        readOnly: true
    example:
      endDate: 2000-01-23
      name: name
      id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      startDate: 2000-01-23
  CorpCust:
    type: object
    properties:
      id:
        type: string
        format: uuid
        description: System generated UUID
      externalId:
        type: string
        description: Unique identifier of the corporate customer in source system.
      enterpriseId:
        type: string
        description: The enterprise this corporate customer is under.
      name:
        type: string
        description: Human readable name for use in identifying the corporate customer.
      address:
        type: object
        properties: {}
      startDate:
        type: string
        format: date
        description: Date that this corporate customer is created
      endDate:
        type: string
        format: date
        description: If the corporate customer is 'deleted', then the end date is set.
        readOnly: true
    example:
      address: '{}'
      endDate: 2000-01-23
      name: name
      externalId: externalId
      id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      enterpriseId: enterpriseId
      startDate: 2000-01-23
  Company:
    type: object
    properties:
      id:
        type: string
        format: uuid
        description: System generated UUID
      externalId:
        type: string
        description: Unique identifier of the company in source system.
      corpcustId:
        type: string
        description: The corporate customer this company belongs to.
      name:
        type: string
        description: Human readable name for use in identifying the company.
      address:
        type: object
        properties: {}
      startDate:
        type: string
        format: date
        description: Date that this company is created
      endDate:
        type: string
        format: date
        description: If the company is 'deleted', then the end date is set.
        readOnly: true
    example:
      corpcustId: corpcustId
      address: '{}'
      endDate: 2000-01-23
      name: name
      externalId: externalId
      id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      startDate: 2000-01-23
  Client:
    type: object
    required:
    - source
    properties:
      id:
        type: string
        format: uuid
        description: System generated UUID
      source:
        type: string
        description: |
          Source system for identifying actual provisioned client. This value must be one of the supported
          systems in order to tie license information to specific, supported provisioning systems for purposes
          of license creation.
        enum:
        - gm5
        - mavenir
        - somethingElse
        - talkpoint
      externalId:
        type: string
        description: Unique identifier of client in source system. May not apply for unlinked/unprovisioned client sources..
      name:
        type: string
        description: Hooman readable name for use in identifying client records. (Admin use only?? Synchronizing? etc)
      companyId:
        type: string
        description: This client's company
      address:
        type: object
        example:
          address1: 2300 Lakeview Parkway
          city: Alpharetta
          stateOrProvince: GA
          postalCode: 30009
          country: USA
        properties: {}
      startDate:
        type: string
        format: date
        description: Date that this client is assigned to the current license
      endDate:
        type: string
        format: date
        description: |
          If the client assignment to the license is 'deleted', then the end date
          is set.
        readOnly: true
    example:
      companyId: companyId
      address:
        address1: 2300 Lakeview Parkway
        city: Alpharetta
        stateOrProvince: GA
        postalCode: 30009
        country: USA
      endDate: 2000-01-23
      name: name
      externalId: externalId
      id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      source: gm5
      startDate: 2000-01-23
