---
swagger: "2.0"
info:
  description: This is the PGi Client API
  version: 1.0.0
  title: PGi Client API
  contact:
    email: mark.peppers@pgi.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /mpeppers/PGiClientAPI/1.0.0
tags:
- name: internal
  description: Internal PGi admin calls
- name: external
  description: API calls available to external resources
schemes:
- https
paths:
  /client/{id}:
    get:
      tags:
      - internal
      - external
      summary: Get a Client by Id
      description: return the requested Client
      operationId: getClient
      parameters:
      - name: id
        in: path
        description: Client Id
        required: true
        type: string
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/Client'
        404:
          description: client not found
    delete:
      tags:
      - internal
      summary: deactivate a client by Id
      operationId: deleteClient
      parameters:
      - name: id
        in: path
        description: Client Id
        required: true
        type: string
      responses:
        200:
          description: success
        202:
          description: client already deactivated
        404:
          description: client not found
  /client/reactivate/{id}:
    put:
      tags:
      - internal
      summary: reactivate a Client by Id
      operationId: reactivateClient
      parameters:
      - name: id
        in: path
        description: Client Id
        required: true
        type: string
      responses:
        200:
          description: success
        202:
          description: client already active
        404:
          description: client not found
  /client:
    post:
      tags:
      - internal
      - external
      summary: adds a Client
      operationId: addClient
      parameters:
      - in: body
        name: newClient
        description: client to add
        required: false
        schema:
          $ref: '#/definitions/Client'
      responses:
        201:
          description: client created
        400:
          description: invalid input, object invalid
    put:
      tags:
      - internal
      - external
      summary: modifies a Client
      operationId: updateClient
      parameters:
      - in: body
        name: updatedClient
        description: updated client
        required: false
        schema:
          $ref: '#/definitions/Client'
      responses:
        200:
          description: client updated
          schema:
            $ref: '#/definitions/Client'
        404:
          description: client not found
definitions:
  Client:
    type: object
    required:
    - source
    properties:
      id:
        type: string
        format: uuid
        description: System generated UUID
      source:
        type: string
        description: |
          Source system for identifying actual provisioned client. This value must be one of the supported
          systems in order to tie license information to specific, supported provisioning systems for purposes
          of license creation.
        enum:
        - gm5
        - mavenir
        - somethingElse
        - talkpoint
      externalId:
        type: string
        description: Unique identifier of client in source system. May not apply for unlinked/unprovisioned client sources..
      name:
        type: string
        description: Hooman readable name for use in identifying client records. (Admin use only?? Synchronizing? etc)
      startDate:
        type: string
        format: date
        description: Date that this client is assigned to the current license
      endDate:
        type: string
        format: date
        description: |
          If the client assignment to the license is 'deleted', then the end date
          is set.
        readOnly: true
    example:
      endDate: 2000-01-23
      name: name
      externalId: externalId
      id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      source: gm5
      startDate: 2000-01-23
