---
swagger: "2.0"
info:
  description: This is the license API
  version: 1.0.0
  title: PGi License API
  contact:
    email: mark.peppers@pgi.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /mpeppers/LicenseAPI/1.0.0
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
schemes:
- https
paths:
  /contract:
    get:
      tags:
      - License Mgmt - external
      - License Mgmt - internal
      description: |
        Lists all contracts which are active and belong to the same enterprise as the current user, or all for super-users.
      operationId: listContracts
      parameters:
      - name: enterpriseid
        in: query
        description: Optional filter to only retrieve contracts assigned to a specific enterprise
        required: false
        type: string
      responses:
        200:
          description: List of contracts matching the enterprise, or empty list if none.
          schema:
            type: array
            items:
              $ref: '#/definitions/Contract'
        401:
          description: Not Authenticated
        403:
          description: Not authorized to view contracts for the requested enterprise
        500:
          description: Server error
    post:
      tags:
      - License Mgmt - internal
      summary: Create a new Contract
      description: Adds a Contract to the system
      operationId: addContract
      parameters: []
      responses:
        201:
          description: Contract Created
        400:
          description: Invalid input. Check error response for additional details
        409:
          description: Contract already exists for this externalId
        401:
          description: Not Authenticated
        403:
          description: Not authorized to view contracts for the requested enterprise
        500:
          description: Internal Server Error
  /contract/{id}/licenseset:
    get:
      tags:
      - License Mgmt - internal
      - License Mgmt - external
      summary: List all licenseSets for contract
      description: List all license-able components for a particular contract
      operationId: listLicenseSets
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        200:
          description: Success. If no results found, empty list
          schema:
            type: array
            items:
              $ref: '#/definitions/LicenseSet'
        404:
          description: Not found
    post:
      tags:
      - License Mgmt - internal
      summary: Create license set
      description: Adds a new licenseSet under the specified contract
      operationId: addLicenseSet
      parameters:
      - name: id
        in: path
        required: true
        type: string
      - in: body
        name: newLicense
        required: true
        schema:
          $ref: '#/definitions/LicenseSet'
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/LicenseSet'
  /contract/{contractId}/licenseset/{licenseSetId}:
    get:
      tags:
      - License Mgmt - internal
      - License Mgmt - external
      summary: List all licenseSets for contract
      description: List all license-able components for a particular contract
      operationId: listLicenseSetsByContract
      parameters:
      - name: contractId
        in: path
        description: Id of the enterprise contract.
        required: true
        type: string
      - name: licenseSetId
        in: path
        description: Id of the License Set.
        required: true
        type: string
      responses:
        200:
          description: Success.
          schema:
            $ref: '#/definitions/LicenseSet'
        404:
          description: Not found
    patch:
      tags:
      - License Mgmt - internal
      summary: Update limited licenseSet details
      description: |
        Internal usage only to modify some attributes: may include
        updates to the model and model properties. (No access to options available...)
      parameters:
      - name: contractId
        in: path
        description: Id of the enterprise contract.
        required: true
        type: string
      - name: licenseSetId
        in: path
        description: Id of the License Set.
        required: true
        type: string
      - in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/TODO'
      responses:
        200:
          description: Success.
          schema:
            $ref: '#/definitions/LicenseSet'
        404:
          description: Not found
definitions:
  Contract:
    type: object
    required:
    - default
    - enterpriseId
    - externalId
    - name
    - source
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
        description: System generated UUID. You are not able to create or update this value via the API. It is ignored in all PUT/POST/PATCH methods
        readOnly: true
      name:
        type: string
        example: Hosted Voice with Global Meet
        maxLength: 256
      source:
        type: string
        description: Source system for contract creation/ownership
        enum:
        - iContract
      externalId:
        type: string
        format: uuid
        example: a023800000ZUQCW
        description: Unique identifier from source system, like the salesforce iContract id.
      enterpriseId:
        type: string
        description: Id of top level enterprise. User authorization must include access rights to the enterprise to access contracts.
      default:
        type: boolean
        description: |
          Flag to determine if this is the default contract to be used for operations. If you update this flag to
          be true, then all other contracts belonging to the enterprise will be set to default=false
    description: |
      Represents the base Contract (Agreement), which is assigned to an Enterprise (top level of company
      heirarchy)
    example:
      default: true
      name: Hosted Voice with Global Meet
      externalId: a023800000ZUQCW
      id: d290f1ee-6c54-4b01-90e6-d701748f0851
      source: iContract
      enterpriseId: enterpriseId
  LicenseSet:
    type: object
    required:
    - model
    - name
    properties:
      name:
        type: string
        example: Global Meet
        maxLength: 256
      id:
        type: string
        format: uuid
        description: System generated UUID
        readOnly: true
      externalId:
        type: string
        description: External System id. Sent in processing messages
      contractId:
        type: string
        description: Contract to which this sub component (license set) belongs. A single contract may contain multiple, independently licensable products.
        readOnly: true
      model:
        type: string
        description: 'License model that is applied to the component. Master Service
          Agreement, fixed license count, min/max license:'
        enum:
        - msa
        - fixed
        - minMax
      modelProperties:
        type: array
        description: 'Array of properties that associated to alicense model (i.e.:
          min, max). Values are dependent on license model used'
        items:
          $ref: '#/definitions/Property'
      features:
        type: array
        description: 'Optional list of features that can be selected during license
          assignment. '
        items:
          $ref: '#/definitions/Feature'
      default:
        type: boolean
        description: Flag to determine if this is the 'default' license set to be used in the UI. No effect on API calls
    example:
      id: 2352-sdf24-235d9-0heyTh3re
      name: Global Meet Web
      externalId: asdfalwirj2o3iruo8u9283u4wej
      contractId: 598e-2kjla4-I3thlkj4
      model: minMax
      modelProperties:
      - min: 30
        max: 50
      features:
      - featureName: participants
        description: Max web participants
        externalId: 123abc-sku
        name: 10 Users
      default: false
  Feature:
    type: object
    required:
    - description
    - name
    properties:
      id:
        type: string
        format: uuid
        description: System assigned name for this feature
      name:
        type: string
        example: Included Minutes
        description: Hooman-readable name for this feature
      description:
        type: string
        description: Hooman-readable description for this feature
      externalId:
        type: string
        example: 2S5srok3x635
        description: Reference ID for this option value. In most cases relates to a rated 'SKU' in a billing system
      option:
        type: string
        example: 1000 min
        description: Human-readable option name
    description: Defines a licence-able product's feature or add-on.
  Property:
    type: object
    required:
    - name
    - value
    properties:
      name:
        type: string
      value:
        type: string
  TODO:
    type: object
    properties:
      thing:
        type: string
    description: all references to this need to be replaced
    example:
      thing: thing
