/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Address (
  /* Address line 1 */
  address1: String,
  /* Address line 2 */
  address2: Option[String],
  /* Address line 3 */
  address3: Option[String],
  city: String,
  /* Only relevant for states that have states or provinces */
  stateOrProvince: Option[String],
  /* ZIP or postal code */
  postalCode: Option[String],
  country: String,
  timeZone: String
) extends ApiModel


