/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Client (
  /* System generated UUID */
  id: Option[UUID],
  /* The client's name */
  name: Option[String],
  /* This client's company */
  companyId: Option[String],
  /* The client's email address */
  email: Option[String],
  address: Option[Address],
  /* Date that this client is assigned to the current license */
  startDate: Option[Date],
  /* If the client assignment to the license is 'deleted', then the end date is set.  */
  endDate: Option[Date]
) extends ApiModel


