/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Contract (
  /* System generated UUID. You are not able to create or update this value via the API. It is ignored in all PUT/POST/PATCH methods */
  id: Option[UUID],
  name: String,
  /* Denotes whether this contract is associated with an legal entity or with a provider */
  contractType: ContractEnums.ContractType,
  /* Id of this contract's associated top-level legal entity or provider, depending on its contractType. */
  entityId: String,
  /* Flag to determine if this is the default contract to be used for operations. If you update this flag to be true, then all other contracts belonging to the legal entity will be set to default=false  */
  default: Boolean
) extends ApiModel

object ContractEnums {

  type ContractType = ContractType.Value
  object ContractType extends Enumeration {
    val LegalEntity = Value("legalEntity")
    val Provider = Value("provider")
  }

}

