/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class License (
  /* System generated UUID for the billable license  */
  licenseId: Option[UUID],
  /* License set id */
  licenseSetId: UUID,
  companyId: Option[String],
  /* Date that this license assignment is in effect. */
  startDate: Option[Date],
  /* Date that this license assignment ends (delete) */
  endDate: Option[Date],
  /* Optional array of license features, if applicable  */
  features: Option[Seq[Feature]],
  /* There are additional licenses that can be assigned in this set. (Based on license model and current data.) This will need to allow for different licensing models (min/max, msa, fixed) and take into account both number of assigned licenses and number of unassigned licenses as part of the calculation.  */
  canAdd: Option[Boolean],
  /* License Assignments represent the recent history of all client Ids that have been assigned to this license. These records are primary used by Mediation Clients to map received CDR data to the appropriate billable license  */
  licenseAssignments: Option[Seq[Client]]
) extends ApiModel


