/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class LicenseSet (
  name: String,
  /* System generated UUID */
  id: Option[UUID],
  /* Contract to which this sub component (license set) belongs. A single contract may contain multiple, independently licensable products. */
  contractId: Option[String],
  /* In the case of a LicenseSet belonging to a Provider Contract, the provider may assign license sets to multpile legal entity. */
  legalEntityId: Option[String],
  /* License model that is applied to the component. Master Service Agreement, fixed license count, min/max license: */
  model: LicenseSetEnums.Model,
  /* Array of properties that associated to alicense model (i.e.: min, max). Values are dependent on license model used */
  modelProperties: Option[Seq[Property]],
  /* Optional list of features that can be selected during license assignment.  */
  features: Option[Seq[Feature]]
) extends ApiModel

object LicenseSetEnums {

  type Model = Model.Value
  object Model extends Enumeration {
    val Msa = Value("msa")
    val Fixed = Value("fixed")
    val MinMax = Value("minMax")
  }

}

